### ISSUE TITLE
Composer support and config files

### ISSUE THREAD

**Issue by LukeTowers** [OFFLINE-GmbH/oc-cors-plugin#5]
Great work on this plugin @tobias-kuendig! Would you be willing to add composer support and post it on Packagist? 

Also, would it be possible to set it up to pull it's settings from a configuration file as well? These two changes make it easier to integrate with fully git managed projects. Let me know if you're willing to make those changes or if you'd be willing to merge them if I made a PR.

**Comment by tobias-kuendig** [comment]
Thank you, PRs are always welcome.

I have added support for filesystem configuration here: https://github.com/OFFLINE-GmbH/oc-cors-plugin/commit/637c1a4ef4971bacd535e9f242bfdc8d00629ef7

I can register the package on Packagist, are there any conventions concerning October plugins?

**Comment by tobias-kuendig** [comment]
Added here https://packagist.org/packages/offline/oc-cors-plugin and release Version 1.0.3

Feel free to update this issue if any other changes are needed.

**Comment by LukeTowers** [comment]
Awesome, thanks @tobias-kuendig!
